# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details

version: 2

jobs:
  build&pushImage:
    working_directory: ~/appman-demo
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: make gradle commands available
          command: chmod +x gradlew
      - run:
          name: build the binary
          command: ./gradlew build
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.06.0-ce
      - run:
          name: Set the tag for the image, we will concatenate the app verson and circle build number with a `-` char in between
          command:  echo 'export TAG=0.0.2-$CIRCLE_BUILD_NUM' >> $BASH_ENV
      - run:
          name: echo tag
          command: echo $TAG
      - run:
          name: Build the docker image
          command: docker build . -t ${CIRCLE_PROJECT_REPONAME}:$TAG --build-arg JAR_FILE=build/libs/*.jar
      - run:
          name: Login to DockerHub
          command: docker login -u ${DOCKER_HUB_UNAME} -p ${DOCKER_HUB_PW}
      - run:
          name: Tag the image with docker hub repo name
          command: docker tag ${CIRCLE_PROJECT_REPONAME}:$TAG ${DOCKER_HUB}:$TAG
      - run:
          name: Push the image the docker hub
          command: docker push ${DOCKER_HUB}:$TAG

workflows:
  version: 2
  primary:
    jobs:
      - build&pushImage