# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details

version: 2.1

general:
  tag:
    only:
      - master
      - dev

jobs:
  build&pushImage:
    tag: /v[0-9]+(\.[0-9]+)*(-.*)*/
    working_directory: ~/appman-demo
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: make gradle commands available
          command: chmod +x gradlew
      - run:
          name: build the binary
          command: ./gradlew build
      - setup_remote_docker:
          docker_layer_caching: false
          version: 18.06.0-ce
      - run:
          name: Build the docker image
          command: docker build . -t ${CIRCLE_PROJECT_REPONAME}:$TAG --build-arg JAR_FILE=build/libs/*.jar
      - run:
          name: Login to DockerHub
          command: docker login -u ${DOCKER_HUB_UNAME} -p ${DOCKER_HUB_PW}
      - run:
          name: Tag the image with docker hub repo name
          command: docker tag ${CIRCLE_PROJECT_REPONAME}:$TAG ${DOCKER_HUB_UNAME}/${CIRCLE_PROJECT_REPONAME}-$CIRCLE_BRANCH:$CIRCLE_TAG
      - run:
          name: Push the image the docker hub
          command: docker push ${DOCKER_HUB_UNAME}/${CIRCLE_PROJECT_REPONAME}-$CIRCLE_BRANCH:$CIRCLE_TAG

workflows:
  version: 2.1
  primary:
    jobs:
      - build&pushImage