apiVersion: apps/v1
kind: Deployment
metadata:
  name: appman-demo
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: appman-demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: appman-demo
    spec:
      containers:
        - image: brechtpallemans/appman-demo:0.0.2-28
          imagePullPolicy: Always
          name: appman-demo
          ports:
            - containerPort: 80